MASTER_UNLOCK_GRID = [
    {"unlock": "Rocket Launcher (tutorial)", "condition": "Level 1.5 vs Brutus Base Form", "code": None, "reward": "Heavy weapon slot unlocked"},
    {"unlock": "StarGun Lv2", "condition": "Beat Casino Siege boss (L6)", "code": None, "reward": "Burst fire pistol"},
    {"unlock": "Heat Thermo Tux", "condition": "Earned at finale cutscene (L7)", "code": None, "reward": "Future armor upgrade"},
    {"unlock": "Flamethrower", "condition": "Beat game once (NG+)", "code": "FIREWALL", "reward": "Wide arc crowd control"},
    {"unlock": "Brutus (Playable)", "condition": "Beat game twice", "code": "BRUTAL", "reward": "Tank character"},
    {"unlock": "Phantom (Playable)", "condition": "Beat game three times", "code": "PHANT0M", "reward": "Overpowered melee/dash"},
    {"unlock": "Xyra (Playable)", "condition": "Rescue w/ no damage in Casino Siege → enter STARQUEEN", "code": "STARQUEEN", "reward": "Agile pistol/acrobat"},
    {"unlock": "Manny Drone (Playable)", "condition": "Perfect clear in ISO Strike intro/outro twice", "code": "GEARHEAD", "reward": "Energy blasts, hover dash"},
    {"unlock": "Syndicate Guard", "condition": "Flawless stealth run in Docks → enter FACEOFF", "code": "FACEOFF", "reward": "Rifle + baton kit"},
    {"unlock": "Casino High-Roller", "condition": "Win max payout in baccarat", "code": "STACKEDDECK", "reward": "Gag kit (chips/champagne)"},
    {"unlock": "Guard Dog (AI companion)", "condition": "Distract-only stealth clear in Docks", "code": None, "reward": "AI ally dog companion"},
    {"unlock": "Phantom’s Blade (skin)", "condition": "Perfect parries in Phantom duel", "code": None, "reward": "Cosmetic knife skin"},
    {"unlock": "Silent Boots", "condition": "3x fast hack clears (<10s)", "code": "SILENTSTEP", "reward": "Noise reduced"},
    {"unlock": "Golden Chip", "condition": "Max payout streak in casino", "code": "BLACKJACK", "reward": "Bonus credits per mission"},
    {"unlock": "Hard Mode", "condition": "Enter code only", "code": "PHANTOM", "reward": "+25% dmg enemies"},
    {"unlock": "Mech Arena", "condition": "Enter code only", "code": "BRUTUS", "reward": "Test fight mode"},
    {"unlock": "Visual Filter", "condition": "Enter code only", "code": "NEONNIGHT", "reward": "Neon shader"},
]
